#cloud-config

users:
- name: gcer
  uid: 2000

write_files:
- path: /etc/gcer/startup.sh
  permissions: 0755
  owner: root
  content: |
%s
- path: /etc/systemd/system/gcer.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=RStudio Docker startup
    Requires=docker.service
    After=docker.service
    
    [Service]
    Restart=always
    Environment="HOME=/home/gcer"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries=asia.gcr.io,eu.gcr.io,gcr.io,marketplace.gcr.io,us.gcr.io,docker.pkg.dev,us-docker.pkg.dev,eu-docker.pkg.dev,asia-docker.pkg.dev
    ExecStart=/etc/gcer/startup.sh
    ExecStop=/usr/bin/docker stop rstudio
    ExecStopPost=/usr/bin/docker rm rstudio
    
runcmd:
- systemctl daemon-reload
- systemctl start gcer.service
