#' Retrieves the list of instances contained within the specified zone.
#' 
#' 
#' @seealso \href{https://developers.google.com/compute/docs/reference/latest/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/compute
#' \item https://www.googleapis.com/auth/compute.readonly
#' }
#' 
#' 
#' @param project Project ID for this request
#' @param zone The name of the zone for this request
#' @param filter Sets a filter expression for filtering listed resources, in the form filter={expression}
#' @param maxResults The maximum number of results per page that should be returned
#' @param pageToken Specifies a page token to use
#' @importFrom googleAuthR gar_api_generator
#' @export
gce_list_instances <- function(project, 
                               zone, 
                               filter = NULL, 
                               maxResults = NULL, 
                               pageToken = NULL) {
  url <- sprintf("https://www.googleapis.com/compute/v1/projects/%s/zones/%s/instances", 
                 project, zone)
  pars <- list(filter = filter, 
               maxResults = maxResults, 
               pageToken = pageToken)
  pars <- rmNullObs(pars)
  # compute.instances.list
  f <- gar_api_generator(url, 
                         "GET", 
                         pars_args = pars, 
                         data_parse_function = function(x) x)
  f()
  
}

#' Returns the specified Instance resource.
#' 
#' 
#' @seealso \href{https://developers.google.com/compute/docs/reference/latest/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/compute
#' \item https://www.googleapis.com/auth/compute.readonly
#' }
#' 
#' 
#' @param project Project ID for this request
#' @param zone The name of the zone for this request
#' @param instance Name of the instance resource to return
#' @importFrom googleAuthR gar_api_generator
#' @export
gce_get_instance <- function(project, 
                             zone, 
                             instance) {
  
  url <- sprintf("https://www.googleapis.com/compute/v1/projects/%s/zones/%s/instances/%s", 
                 instance, project, zone)
  # compute.instances.get
  f <- gar_api_generator(url, 
                         "GET", 
                         data_parse_function = function(x) x)
  f()
  
}

#' InstancesSetMachineTypeRequest Object
#' 
#' @details 
#' Autogenerated via \code{\link[googleAuthR]{gar_create_api_objects}}
#' No description
#' 
#' @param machineType Full or partial URL of the machine type resource
#' 
#' @return InstancesSetMachineTypeRequest object
#' 
#' @family InstancesSetMachineTypeRequest functions
#' @keywords internal
InstancesSetMachineTypeRequest <- function(machineType = NULL) {
  
  structure(list(machineType = machineType), 
            class = "gar_InstancesSetMachineTypeRequest")
}

#' Changes the machine type for a stopped instance to the machine type specified in the request.
#' 
#' 
#' @seealso \href{https://developers.google.com/compute/docs/reference/latest/}{Google Documentation}
#' 
#' @details 
#' Authentication scopes used by this function are:
#' \itemize{
#'   \item https://www.googleapis.com/auth/cloud-platform
#' \item https://www.googleapis.com/auth/compute
#' }
#' 
#' @param machineType Full or partial URL of the machine type resource
#' @param project Project ID for this request
#' @param zone The name of the zone for this request
#' @param instance Name of the instance scoping this request
#' @importFrom googleAuthR gar_api_generator
#' @family InstancesSetMachineTypeRequest functions
#' @export
gce_set_machinetype <- function(machineType, 
                                     project, 
                                     zone, 
                                     instance) {
  
  url <- sprintf("https://www.googleapis.com/compute/v1/projects/%s/zones/%s/instances/%s/setMachineType", 
                 instance, project, zone)
  
  the_machine <- InstancesSetMachineTypeRequest(machineType = machineType)
  # compute.instances.setMachineType
  f <- gar_api_generator(url, 
                         "POST", 
                         data_parse_function = function(x) x)
  
  stopifnot(inherits(the_machine, "gar_InstancesSetMachineTypeRequest"))
  
  f(the_body = the_machine)
  
}